title: My Jekyll Site
description: SAIL Research Group
url: "https://sail-research.com"  # the base hostname & protocol for your site
baseurl: ""  # the subpath of your site, e.g. /blog
markdown: kramdown

include:
  - _pages
  - projects/
# # Plugins (if needed)
# plugins:
#   - jekyll-feed
#   - jekyll-seo-tag

# Optional: Specify the theme if you're using one
# theme: minima  # Uncomment if using a theme
