title: My Jekyll Site
description: SAIL Research Group
url: https://sail-research.github.io
baseurl: ""  # Leave blank if you are deploying to the root domain
markdown: kramdown

# Build settings
permalink: pretty
theme: minima  # Change this to your preferred theme

# Plugins (if needed)
plugins:
  - jekyll-feed
  - jekyll-seo-tag
