title: My Jekyll Site
description: SAIL Research Group
url: https://sail-research.github.io
baseurl: "/sail-research"  # Change this to your repository name if deploying on GitHub Pages
markdown: kramdown

include:
  - _pages
# # Plugins (if needed)
# plugins:
#   - jekyll-feed
#   - jekyll-seo-tag

# Optional: Specify the theme if you're using one
# theme: minima  # Uncomment if using a theme
