name: Deploy Jekyll Site

on:
  push:
    branches:
      - main  # Change to your default branch if it's different
  workflow_dispatch:  # Allows manual triggering of the workflow

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # Ensure write permissions for the GITHUB_TOKEN

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.1'  # Specify your Ruby version here

      - name: Install dependencies
        run: |
          gem install bundler
          bundle install

      - name: Build the site
        run: |
          bundle exec jekyll build

      - name: Upload the built site
        uses: actions/upload-artifact@v3
        with:
          name: github-pages
          path: ./_site  # Default output directory for Jekyll

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write
      contents: write  # Ensure write permissions for the GITHUB_TOKEN
    steps:
      - name: Download the built site
        uses: actions/download-artifact@v3
        with:
          name: github-pages

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_site  # Ensure the correct path to your built site
